/**
 * Stable, machine-readable error codes returned as `error.code`.
 *
 * These are part of the public API contract: clients branch on them instead of
 * string-matching `error.message`. Treat this list as **append-only** — never
 * rename a code and never reuse a retired one.
 *
 * A `const` object plus a derived union (rather than a TS `enum`) keeps the
 * CommonJS emit trivial and lets shell/smoke tests compare plain strings.
 */
export const ErrorCodes = {
  // Transport / generic
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  MALFORMED_JSON: "MALFORMED_JSON",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  // Input
  INVALID_ID: "INVALID_ID",
  MISSING_FIELD: "MISSING_FIELD",
  INVALID_FIELD: "INVALID_FIELD",

  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",

  // PMN
  PMN_SCUM_RULE_VIOLATION: "PMN_SCUM_RULE_VIOLATION",
  PMN_RECORD_NOT_FOUND: "PMN_RECORD_NOT_FOUND",
  PMN_SCUM_PHOTO_NOT_FOUND: "PMN_SCUM_PHOTO_NOT_FOUND",
  PMN_READ_FAILED: "PMN_READ_FAILED",
  PMN_CREATE_FAILED: "PMN_CREATE_FAILED",
  PMN_UPDATE_FAILED: "PMN_UPDATE_FAILED",
  PMN_DELETE_FAILED: "PMN_DELETE_FAILED",
  PMN_SCUM_LOOKUP_FAILED: "PMN_SCUM_LOOKUP_FAILED",

  // Watershed / phosphate
  PHOSPHATE_RECORD_NOT_FOUND: "PHOSPHATE_RECORD_NOT_FOUND",
  PHOSPHATE_LOCATION_UNKNOWN: "PHOSPHATE_LOCATION_UNKNOWN",
  PHOSPHATE_READ_FAILED: "PHOSPHATE_READ_FAILED",
  PHOSPHATE_CREATE_FAILED: "PHOSPHATE_CREATE_FAILED",
  PHOSPHATE_UPDATE_FAILED: "PHOSPHATE_UPDATE_FAILED",
  PHOSPHATE_DELETE_FAILED: "PHOSPHATE_DELETE_FAILED",

  // Users
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EMAIL_TAKEN: "USER_EMAIL_TAKEN",
  USER_ROLE_UNKNOWN: "USER_ROLE_UNKNOWN",
  USERS_READ_FAILED: "USERS_READ_FAILED",
  USERS_CREATE_FAILED: "USERS_CREATE_FAILED",
  USERS_UPDATE_FAILED: "USERS_UPDATE_FAILED",
  USERS_DELETE_FAILED: "USERS_DELETE_FAILED",

  // Uploads
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  UPLOADS_PRESIGN_FAILED: "UPLOADS_PRESIGN_FAILED",
  UPLOADS_CONFIRM_FAILED: "UPLOADS_CONFIRM_FAILED",
  UPLOADS_DOWNLOAD_URL_FAILED: "UPLOADS_DOWNLOAD_URL_FAILED",
  UPLOADS_LIST_FAILED: "UPLOADS_LIST_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
