// Location seed data for the watershed_field_data.locations table.
//
// Populate this array with the provided data. `loc_name`, `latitude`, and
// `longitude` are required; `description` is optional. `loc_id` is generated by
// the database, so do not set it here.

export interface LocationSeed {
  loc_name: string;
  latitude: number;
  longitude: number;
  description?: string;
}

export const locations: LocationSeed[] = [
  { loc_name: "Lacamas Lake Downstream", latitude: 45.6, longitude: -122.4, description: "…" },
];
